# Generated by Django 5.1.3 on 2024-11-25 14:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите дату Вашего рождения",
                null=True,
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Введите Ваш номер телефона",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Введите адрес электронной почты",
                max_length=254,
                unique=True,
                verbose_name="Адрес электронной почты",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Введите имя пользователя",
                max_length=50,
                unique=True,
                verbose_name="Никнейм пользователя",
            ),
        ),
    ]
