# Generated by Django 5.1.3 on 2024-11-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_date_of_birth_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Введите адрес электронной почты",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Адрес электронной почты",
            ),
        ),
    ]
