# Generated by Django 5.1.3 on 2024-11-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_tg_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Введите дату Вашего рождения",
                null=True,
                verbose_name="Дата рождения",
            ),
        ),
    ]
