version: '3'

services:
  db:
    image: postgres:16-alpine
    # перезагружает контейнер postgres после падения
    restart: on-failure
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - pg_data:var/lib/postgresql/data
    # проверка на то что postgres запущен
    healthcheck:
      test: [ 'CMD-SHELL', '-c', 'pg_isready -U $POSTGRES_USER' ]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    # для интерактивного режима
    tty: true
    command: sh -c 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - '8000:8000'
    # контейнер с зависимостями
    depends_on:
      db:
        condition: service_healthy
    # чтобы данные текущей директории прокидывались в директорию app
    volumes:
      - .:/app

volumes:
  pg_data:




