# Generated by Django 5.1.3 on 2024-11-22 12:49

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место привычки",
                        max_length=255,
                        null=True,
                        verbose_name="Место привычки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Укажите время, когда необходимо выполнять привычку",
                        verbose_name="Время для привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие для привычки",
                        max_length=255,
                        verbose_name="Действие для привычки",
                    ),
                ),
                (
                    "start_day",
                    models.DateTimeField(
                        verbose_name="День начала выполнения привычки"
                    ),
                ),
                (
                    "next_day",
                    models.DateTimeField(
                        blank=True, verbose_name="День следующей выполнения привычки"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Укажите будет ли привычка приятной",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Укажите периодичность привычки в днях",
                        verbose_name="Периодичность привычки в днях",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение за привычку",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение за привычку",
                    ),
                ),
                (
                    "time_to_complete",
                    models.TimeField(
                        blank=True,
                        default=datetime.timedelta(seconds=120),
                        help_text="Укажите время на выполнение привычки (не более 2 мин)",
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Укажите будет ли привычка публичной",
                        verbose_name="Публичность привычки",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная (приятная) привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
