# Generated by Django 5.1.3 on 2024-11-25 16:12

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="time",
            new_name="time_habit",
        ),
        migrations.AlterField(
            model_name="habit",
            name="start_day",
            field=models.DateTimeField(
                verbose_name="День начала выполнения привычки формата год-месяц-день"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.TimeField(
                blank=True,
                default=datetime.time(0, 2),
                help_text="Укажите время на выполнение привычки (не более 2 мин)",
                verbose_name="Время на выполнение привычки",
            ),
        ),
    ]
