# Generated by Django 5.1.3 on 2024-11-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_rename_time_habit_time_habit_alter_habit_start_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="start_day",
            field=models.DateTimeField(
                verbose_name="День начала выполнения привычки в формате год-месяц-день"
            ),
        ),
    ]
