# Generated by Django 5.1.3 on 2024-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_start_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="start_day",
            field=models.DateField(
                verbose_name="День начала выполнения привычки в формате год-месяц-день"
            ),
        ),
    ]
